[workspace]
resolver = "3"
members = [
  "apps/piqueld",
  "apps/piquelctl",
  "apps/piqueld-ui",
  "crates/piqueld-client",
  "crates/piqueld-core",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/piquel-fr/piqueld"
rust-version = "1.96"

[workspace.dependencies]
# Internal
piqueld-client = { version = "0.1.0", path = "crates/piqueld-client" }
piqueld-core   = { version = "0.1.0", path = "crates/piqueld-core"   }

# External
anyhow = "1.0.98"
async-trait = "0.1.88"
axum = { version = "0.8.4", features = ["json", "tokio", "http1"] }
bytes = "1.10.1"
futures-util = "0.3.31"
http = "1.3.1"
http-body-util = "0.1.3"
hyper = { version = "1.6.0", features = ["client", "http1"] }
hyper-util = { version = "0.1.14", features = ["tokio"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_path_to_error = "0.1.17"
schemars = { version = "0.8.22", features = ["derive"] }
sha2 = "0.10.9"
sqlx = { version = "0.8.6", default-features = false, features = ["macros", "runtime-tokio", "sqlite"] }
tempfile = "3.20.0"
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["fs", "macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
tokio-util = { version = "0.7.15", features = ["rt"] }
toml = "0.8.22"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt", "json"] }
tower = { version = "0.5.2", features = ["util"] }
tower-http = { version = "0.6.6", features = ["request-id", "trace"] }
utoipa = { version = "5.3.1", features = ["axum_extras", "uuid"] }
url = "2.5.4"
uuid = { version = "1.17.0", features = ["v7"] }

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"

[profile.release]
lto = "thin"
strip = "symbols"
