[advisories]
unmaintained = "workspace"

[bans]
multiple-versions = "warn"
wildcards = "deny"

[licenses]
confidence-threshold = 0.8
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "ISC",
  "MIT",
  "Unicode-3.0",
]

[sources]
unknown-git = "deny"
unknown-registry = "deny"
