//! `SQLite` persistence and atomic acceptance of validated application and
//! environment commands; Docker planning and execution belong to the controller.

mod acceptance;
mod access;
mod application;
mod audit;
mod auth;
mod build;
mod deployment;
mod environment;
mod event;
pub(crate) mod ingress;
mod jobs;
mod journal;
mod notifications;
mod observability;
pub use access::{Actor, Attribution, Caller, Visibility};
pub(crate) use audit::NewAuditEvent;
pub use auth::{CredentialKind, Lockout};
pub(crate) use auth::{Invitation, NewCredential, NewInvitation, NewPasskey, PasskeyOwner};
pub(crate) use journal::JournalAction;
mod operation;
mod repository;
mod secret;
mod status;

use piqueld_core::{
    ApplicationId, EnvironmentId, EnvironmentName, EnvironmentSource, NormalizedApplication,
    TrackedBranch,
    api::EnvironmentView,
    manifest::{
        ApplicationTemplate, ManifestRevision, RenderContext, Rendering, RepositoryManifest,
    },
    resource::ResolvedApplication,
};
pub use piqueld_core::{ApplicationState, Operation, OperationKind, OperationState};
use sqlx::{
    Sqlite, SqlitePool, Transaction,
    sqlite::{SqliteConnectOptions, SqliteJournalMode, SqlitePoolOptions},
};
use std::{
    error::Error as StdError,
    fs,
    path::Path,
    sync::atomic::{AtomicI64, Ordering},
    time::{Duration, SystemTime, UNIX_EPOCH},
};
use thiserror::Error;
use uuid::Uuid;

/// Expands to the migration list generated by `build.rs` from the workspace `migrations`
/// directory, as a `&[&str]` of SQL scripts in apply order.
macro_rules! include_migrations {
    () => {
        include!(concat!(env!("OUT_DIR"), "/migrations.rs"))
    };
}
/// Embedded forward migrations; migration `i` upgrades schema `i` to `i + 1`.
const MIGRATIONS: &[&str] = include_migrations!();
/// Latest database schema, equal to the number of embedded migrations.
pub const SCHEMA_VERSION: u64 = MIGRATIONS.len() as u64;

/// Persistence failures with stable classifications and retained source detail.
#[derive(Debug, Error)]
pub enum StoreError {
    /// A field edit does not apply to the saved configuration.
    #[error(transparent)]
    Edit(#[from] piqueld_core::edit::EditError),
    /// The edited manifest fails semantic validation.
    #[error(transparent)]
    Validation(#[from] piqueld_core::ValidationErrors),
    /// Secret ciphertext or its master key could not be used.
    #[error("secret storage is unavailable")]
    SecretSource(#[source] anyhow::Error),
    /// Required values were discarded during lost-key recovery.
    #[error(
        "secret values unavailable: {names}; supply replacement values and start a new deployment"
    )]
    SecretUnavailable {
        /// Logical names only, never values.
        names: String,
    },
    /// Lost-key recovery was requested, but the current key still works.
    #[error("the secret master key still works; recovery would discard values needlessly")]
    SecretKeyUsable,
    /// Saved configuration or a retained deployment still refers to the secret.
    #[error("secret is still referenced by application configuration or deployment")]
    SecretReferenced,
    /// Runtime cleanup is pending and may already have removed some versions.
    #[error("secret deletion is in progress; retry deletion to finish cleanup")]
    SecretDeleting,
    /// Retained ciphertext is bounded without evicting deployment pins.
    #[error(
        "secret storage quota exceeded (1000 versions or 100 MiB per environment); delete unused secrets to free space"
    )]
    SecretQuota,
    /// A secret changed after the caller inspected its metadata.
    #[error("secret generation changed: expected {expected}, actual {actual}")]
    SecretVersionConflict {
        /// Version supplied by the caller.
        expected: i64,
        /// Current logical secret version.
        actual: i64,
    },
    /// An exact public hostname belongs to another environment or the installation.
    #[error("hostname {hostname} is reserved by another environment or this installation")]
    HostnameConflict {
        /// Conflicting canonical public hostname.
        hostname: String,
    },
    /// Another environment of the same application renders the same hostname.
    #[error(
        "hostname {hostname} is reserved by environment {environment} of this application; give each environment its own hostname, e.g. `hostname = \"${{{{ vars.domain }}}}\"` with a different `domain` per environment"
    )]
    SharedHostnameConflict {
        /// Conflicting canonical public hostname.
        hostname: String,
        /// Sibling environment holding the reservation.
        environment: EnvironmentName,
    },
    /// A storage operation failed without a lower-level source.
    #[error("database operation failed")]
    Database,
    /// A storage operation failed in `SQLx`.
    #[error("database operation failed")]
    DatabaseSource(#[source] sqlx::Error),
    /// The database schema is newer or otherwise incompatible.
    #[error("database schema is incompatible")]
    SchemaMismatch,
    /// Schema metadata could not be read or decoded.
    #[error("database schema is incompatible")]
    SchemaMismatchSource(#[source] Box<dyn StdError + Send + Sync>),
    /// The configured database path could not be prepared safely.
    #[error("database path could not be prepared")]
    PathSource(#[source] std::io::Error),
    /// A requested row does not exist.
    #[error("resource was not found")]
    NotFound,
    /// The requested intent revision is stale.
    #[error("application generation conflict: expected {expected}, actual {actual}")]
    GenerationConflict {
        /// Requested revision.
        expected: u64,
        /// Current revision; zero means absent.
        actual: u64,
    },
    /// The name no longer selects the application inspected by the caller.
    #[error("application identity changed since inspection")]
    IdentityConflict,
    /// A request ID was already used for different input.
    #[error("request ID was already used for different input")]
    ReplayConflict,
    /// Mutation cannot run during pending work or deletion.
    #[error("application is busy; wait for its current operation to finish")]
    Busy,
    /// A runtime command named an application whose environment is ambiguous.
    #[error(
        "environment required: the application has {}; name one explicitly",
        environment_list(environments)
    )]
    EnvironmentRequired {
        /// The application's environments, in name order.
        environments: Vec<EnvironmentName>,
    },
    /// Deleting an application with several environments must name every one.
    #[error(
        "deleting this application also deletes {}; confirm by naming every environment",
        environment_list(environments)
    )]
    ConfirmationRequired {
        /// The application's environments, in name order.
        environments: Vec<EnvironmentName>,
    },
    /// Runtime fields are managed by the repository manifest.
    #[error("application configuration is managed by its repository manifest")]
    RepositoryManaged,
    /// Renaming would change which `[spec.environments.<name>]` block applies.
    #[error(
        "the saved manifest configures [spec.environments.{environment}]; renaming would change which configuration applies, so remove that block from the manifest first and add it back under the new name after renaming"
    )]
    EnvironmentConfigured {
        /// Old or new name that has a block.
        environment: EnvironmentName,
    },
    /// A unique logical name or identifier already exists.
    #[error("resource already exists")]
    AlreadyExists,
    /// The account change would leave nobody able to administer the installation.
    #[error(transparent)]
    Lockout(#[from] Lockout),
    /// The caller may not perform the change.
    #[error(transparent)]
    Denied(piqueld_core::access::Denied),
    /// The caller's credential was revoked or expired during the request.
    #[error("the credential was revoked")]
    CredentialRevoked,
    /// Persisted state has inconsistent identity.
    #[error("stored application state is corrupt")]
    Corrupt,
    /// Persisted state could not be decoded into its domain representation.
    #[error("stored application state is corrupt")]
    CorruptSource(#[source] Box<dyn StdError + Send + Sync>),
    /// The requested durable state transition is illegal.
    #[error("illegal durable state transition")]
    IllegalTransition,
    /// A repository command contained invalid input.
    #[error("repository input is invalid")]
    InvalidInput,
    /// Requested stream history was pruned.
    #[error("requested event history is no longer available")]
    HistoryExpired,
    /// Repository input could not be converted to its bounded representation.
    #[error("repository input is invalid")]
    InvalidInputSource(#[source] Box<dyn StdError + Send + Sync>),
}

/// Describes environments in an error message.
///
/// ```text
/// []                      -> "no environments"
/// [production, staging]   -> "environments production, staging"
/// ```
fn environment_list(environments: &[EnvironmentName]) -> String {
    if environments.is_empty() {
        return "no environments".into();
    }
    let names = environments
        .iter()
        .map(EnvironmentName::as_str)
        .collect::<Vec<_>>();
    format!("environments {}", names.join(", "))
}

impl StoreError {
    /// Wraps an unclassified `SQLx` failure.
    fn database(source: sqlx::Error) -> Self {
        Self::DatabaseSource(source)
    }

    /// Classifies constraint violations on writes that name or reference rows.
    fn constraint(source: sqlx::Error) -> Self {
        match source.as_database_error() {
            Some(error) if error.is_unique_violation() => Self::AlreadyExists,
            Some(error) if error.is_foreign_key_violation() => Self::NotFound,
            _ => Self::database(source),
        }
    }

    /// Wraps a decoding failure for persisted state that should always be valid.
    pub(crate) fn corrupt(source: impl StdError + Send + Sync + 'static) -> Self {
        Self::CorruptSource(Box::new(source))
    }

    /// Wraps a failure to read or convert schema version metadata.
    fn schema_mismatch(source: impl StdError + Send + Sync + 'static) -> Self {
        Self::SchemaMismatchSource(Box::new(source))
    }

    /// Wraps a caller-supplied value that failed conversion or parsing.
    fn invalid_input(source: impl StdError + Send + Sync + 'static) -> Self {
        Self::InvalidInputSource(Box::new(source))
    }

    /// Wraps an I/O failure while checking the database path.
    fn path(source: std::io::Error) -> Self {
        Self::PathSource(source)
    }
}

/// Persisted application: the manifest its environments share and its revision.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct StoredApplication {
    /// Validated saved manifest, with references unresolved.
    pub application: ApplicationTemplate,
    /// Current configuration revision, shared by every environment.
    pub generation: u64,
    /// Whether the application and all its environments are being deleted.
    pub delete_intent: bool,
    /// When this application was created.
    pub created_at_ms: i64,
    /// When its configuration last changed.
    pub updated_at_ms: i64,
}

/// Persisted environment with the application configuration it deploys.
/// Runtime status is recorded separately.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct StoredEnvironment {
    /// Environment metadata.
    pub environment: EnvironmentView,
    /// Owning application and its saved configuration.
    pub application: StoredApplication,
    /// The manifest last fetched from the environment's branch.
    pub fetched: Option<ApplicationTemplate>,
    /// Resolved Docker target, including immutable image digests.
    pub resolved: Option<ResolvedApplication>,
}

impl StoredEnvironment {
    /// Stable environment identity, from which runtime names derive.
    #[must_use]
    pub fn id(&self) -> &EnvironmentId {
        &self.environment.id
    }

    /// Whether the target is absence of services and networks.
    #[must_use]
    pub fn delete_intent(&self) -> bool {
        self.environment.delete_intent
    }

    /// The manifest this environment deploys, which its hostname
    /// reservations, rename checks, and plans read: the last one fetched from
    /// its branch (`None` before the first fetch), or the application's saved
    /// manifest.
    #[must_use]
    pub fn manifest(&self) -> Option<&ApplicationTemplate> {
        match self.environment.source {
            EnvironmentSource::Saved => Some(&self.application.application),
            EnvironmentSource::Branch(_) => self.fetched.as_ref(),
        }
    }

    /// The application's manifest repository at this environment's branch,
    /// which its deployments fetch.
    #[must_use]
    pub fn repository(&self) -> Option<RepositoryManifest> {
        let connection = self.application.application.spec().manifest.as_ref()?;
        Some(self.environment.source.branch()?.in_repository(connection))
    }

    /// The manifest a new deployment captures: the application's saved one,
    /// fetched instead from [`Self::repository`], at `revision` when given.
    ///
    /// # Errors
    ///
    /// Rejects a revision for an environment without a branch.
    pub fn candidate(
        &self,
        revision: Option<&ManifestRevision>,
    ) -> Result<ApplicationTemplate, StoreError> {
        let template = self
            .application
            .application
            .clone()
            .with_manifest(self.repository());
        Ok(match revision {
            Some(revision) => template.with_manifest_revision(revision)?,
            None => template,
        })
    }

    /// Renders `template` for a deployment of this environment.
    ///
    /// # Errors
    ///
    /// Returns the references without a value here and invalid rendered values.
    pub fn render(
        &self,
        template: &ApplicationTemplate,
        deployment: &str,
    ) -> Result<Rendering, StoreError> {
        Ok(template.render(&RenderContext::deployment(
            self.environment.name.clone(),
            deployment.into(),
        ))?)
    }
}

/// Default query page size.
pub const DEFAULT_PAGE_SIZE: usize = 50;
/// Maximum query page size.
pub const MAX_PAGE_SIZE: usize = 100;

/// Last observed environment status.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EnvironmentStatus {
    /// Environment identity.
    pub environment_id: EnvironmentId,
    /// Current status.
    pub state: ApplicationState,
    /// Last observed runtime health, independent of pending intent.
    pub runtime_health: Option<String>,
    /// Latest diagnostic, when present.
    pub message: Option<String>,
    /// Observation timestamp.
    pub updated_at_ms: i64,
}

/// Page of live environments.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EnvironmentPage {
    /// Environments in ID order.
    pub items: Vec<StoredEnvironment>,
    /// Cursor for the next page.
    pub next_cursor: Option<String>,
}

/// `SQLite` repository shared by the application service and controller.
#[derive(Clone)]
pub struct Store {
    /// Connection pool; readers use it directly, writers go through `writers` first.
    pool: SqlitePool,
    /// Stable installation identity, generated when the database is first created.
    instance_id: String,
    /// Build output retention and per-build byte cap.
    build_history: crate::config::BuildHistoryConfig,

    /// Secret master key file, stored next to the database as `secrets.key`.
    secret_key_path: std::path::PathBuf,
    /// Process-wide writer queue serializing `BEGIN IMMEDIATE` transactions.
    writers: std::sync::Arc<tokio::sync::Mutex<()>>,
    /// Database file path, used to report on-disk size.
    pub(crate) database_path: std::path::PathBuf,
    /// When this store was opened, used to report daemon uptime.
    pub(crate) started: std::time::Instant,
    /// Recently sampled daemon statistics, reused for a few seconds.
    pub(crate) stats_cache:
        std::sync::Arc<tokio::sync::Mutex<Option<piqueld_core::observability::DaemonStats>>>,
    /// Global webhook notification settings.
    pub(crate) notifications: crate::config::NotificationConfig,
    /// Daemon-scoped event retention in days; zero keeps history forever.
    daemon_event_days: u64,
    /// Audit trail retention in days; zero keeps it forever.
    audit_days: u64,
}

impl Store {
    /// Checks whether the database can serve a read, without changing state.
    /// # Errors
    /// Returns the underlying database error when the probe fails.
    pub async fn probe(&self) -> Result<(), StoreError> {
        sqlx::query("SELECT 1")
            .execute(&self.pool)
            .await
            .map_err(StoreError::database)?;
        Ok(())
    }

    /// Opens a local `SQLite` database, applies forward migrations, and creates or loads its instance ID.
    ///
    /// 1. Refuses symlinks and non-regular files at `path`.
    /// 2. Reads `PRAGMA user_version` and rejects databases newer than this binary
    ///    or whose `instance_metadata` disagrees with it.
    /// 3. Applies each pending migration in its own `BEGIN IMMEDIATE` transaction
    ///    (see `apply_migration`), so every committed version is reopenable.
    /// 4. Re-reads and validates the instance ID and recorded schema version.
    ///
    /// # Errors
    /// Returns a sanitized storage or schema compatibility error.
    pub async fn open(path: impl AsRef<Path>) -> Result<Self, StoreError> {
        let path = path.as_ref();
        ensure_database_target(path)?;
        let options = SqliteConnectOptions::new()
            .filename(path)
            .create_if_missing(true)
            .foreign_keys(true)
            .journal_mode(SqliteJournalMode::Wal)
            .busy_timeout(Duration::from_secs(5));
        let pool = SqlitePoolOptions::new()
            .max_connections(8)
            .acquire_timeout(Duration::from_secs(5))
            .connect_with(options)
            .await
            .map_err(StoreError::database)?;

        // SQLite does not expose PRAGMA assignment through bind parameters.
        // The assigned version below comes only from the embedded migrations.
        let version: i64 = sqlx::query_scalar!("PRAGMA user_version")
            .fetch_one(&pool)
            .await
            .map_err(StoreError::database)?
            .ok_or(StoreError::Database)?;
        let version = u64::try_from(version).map_err(StoreError::schema_mismatch)?;
        if version > SCHEMA_VERSION {
            return Err(StoreError::SchemaMismatch);
        }
        if version > 0 {
            let recorded = sqlx::query_scalar!(
                "SELECT schema_version FROM instance_metadata WHERE singleton=1"
            )
            .fetch_optional(&pool)
            .await
            .map_err(StoreError::database)?
            .ok_or(StoreError::SchemaMismatch)?;
            if u64::try_from(recorded).map_err(StoreError::schema_mismatch)? != version {
                return Err(StoreError::SchemaMismatch);
            }
        }

        let migration_start = usize::try_from(version).map_err(StoreError::schema_mismatch)?;
        for (index, migration) in MIGRATIONS.iter().enumerate().skip(migration_start) {
            Self::apply_migration(&pool, index + 1, migration).await?;
        }

        let row = sqlx::query!(
            "SELECT instance_id,schema_version FROM instance_metadata WHERE singleton=1"
        )
        .fetch_optional(&pool)
        .await
        .map_err(StoreError::database)?
        .ok_or(StoreError::Corrupt)?;
        let instance_id = row.instance_id;
        piqueld_core::InstanceId::parse(instance_id.clone()).map_err(StoreError::corrupt)?;
        let metadata_version = u64::try_from(row.schema_version).map_err(StoreError::corrupt)?;
        if metadata_version != SCHEMA_VERSION {
            return Err(StoreError::SchemaMismatch);
        }
        Ok(Self {
            pool,
            instance_id,
            build_history: crate::config::BuildHistoryConfig::default(),

            secret_key_path: path.with_file_name("secrets.key"),
            writers: std::sync::Arc::default(),
            database_path: path.to_path_buf(),
            started: std::time::Instant::now(),
            stats_cache: std::sync::Arc::default(),
            notifications: crate::config::NotificationConfig::default(),
            daemon_event_days: 0,
            audit_days: 0,
        })
    }

    /// Applies one migration and records `version` in a single immediate
    /// transaction, creating the instance identity on the first migration and
    /// updating its schema version afterward.
    async fn apply_migration(
        pool: &SqlitePool,
        version: usize,
        migration: &str,
    ) -> Result<(), StoreError> {
        let mut tx = pool
            .begin_with("BEGIN IMMEDIATE")
            .await
            .map_err(StoreError::database)?;
        sqlx::raw_sql(migration)
            .execute(&mut *tx)
            .await
            .map_err(StoreError::database)?;
        Self::set_user_version(&mut tx, version).await?;
        let generated = format!("instance-{}", Uuid::now_v7().simple());
        let schema_version = i64::try_from(version).map_err(StoreError::schema_mismatch)?;
        let now = now_ms();
        // Every committed boundary is independently reopenable. The first
        // migration creates identity; later migrations preserve it.
        sqlx::query!(
            "INSERT INTO instance_metadata(singleton,instance_id,schema_version,created_at_ms)
             VALUES(1,?1,?2,?3)
             ON CONFLICT(singleton) DO UPDATE SET schema_version=excluded.schema_version",
            generated,
            schema_version,
            now
        )
        .execute(&mut *tx)
        .await
        .map_err(StoreError::database)?;
        tx.commit().await.map_err(StoreError::database)
    }

    /// Sets `PRAGMA user_version` inside a migration transaction.
    async fn set_user_version(
        tx: &mut Transaction<'_, Sqlite>,
        version: usize,
    ) -> Result<(), StoreError> {
        let statement = format!("PRAGMA user_version = {version}");
        // SQLx cannot construct queries for this statement with bindings.
        sqlx::query(&statement)
            .execute(&mut **tx)
            .await
            .map(|_| ())
            .map_err(StoreError::database)
    }

    /// Stable identity of this control-plane database.
    #[must_use]
    pub fn instance_id(&self) -> &str {
        &self.instance_id
    }

    /// Opens a write transaction, returning it with the writer-queue guard that
    /// must be held until commit or rollback.
    /// Writers queue asynchronously before acquiring `SQLite`'s single write lock.
    /// Competing `BEGIN` requests otherwise occupy pool workers and can starve a
    /// transaction under concurrent reconciliation.
    async fn begin_immediate(
        &self,
    ) -> Result<
        (
            tokio::sync::MutexGuard<'_, ()>,
            Transaction<'static, Sqlite>,
        ),
        StoreError,
    > {
        let writer = self.writers.lock().await;
        let tx = self
            .pool
            .begin_with("BEGIN IMMEDIATE")
            .await
            .map_err(StoreError::database)?;
        Ok((writer, tx))
    }
}

/// Verifies the database target is a regular file or absent before `SQLite`
/// creates it. The parent directory's privacy is enforced by the daemon's data
/// directory preparation, not here.
fn ensure_database_target(path: &Path) -> Result<(), StoreError> {
    match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.is_file() && !metadata.is_symlink() => Ok(()),
        Ok(_) => Err(StoreError::path(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "database path is not a regular file",
        ))),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(StoreError::path(error)),
    }
}

/// Last timestamp returned by `now_ms`, keeping it strictly increasing.
static LAST_NOW_MS: AtomicI64 = AtomicI64::new(0);

/// Returns the current Unix time in milliseconds, monotonic within this
/// process so clock step-backs can never violate schema timestamp checks.
pub(crate) fn now_ms() -> i64 {
    let millis = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis();
    let observed = i64::try_from(millis).unwrap_or(i64::MAX);
    let mut last = LAST_NOW_MS.load(Ordering::Relaxed);
    loop {
        let next = last.saturating_add(1).max(observed);
        match LAST_NOW_MS.compare_exchange_weak(last, next, Ordering::Relaxed, Ordering::Relaxed) {
            Ok(_) => return next,
            Err(current) => last = current,
        }
    }
}

/// Returns the current Unix time in seconds, used by authentication records.
/// Unlike `now_ms`, it advances no shared counter, so frequent authentication
/// checks cannot push other timestamps ahead of the clock.
pub(crate) fn now_secs() -> i64 {
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    i64::try_from(secs).unwrap_or(i64::MAX)
}

/// Generates a time-ordered unique identifier with a type prefix.
///
/// ```text
/// new_id("app") -> "app-0192f1c0e4a47d3a9b1c2d3e4f5a6b7c"
/// ```
fn new_id(prefix: &str) -> String {
    format!("{prefix}-{}", Uuid::now_v7().simple())
}

/// Validates a requested page size (`1..=MAX_PAGE_SIZE`) and converts it for binding.
fn page_limit(limit: usize) -> Result<i64, StoreError> {
    if !(1..=MAX_PAGE_SIZE).contains(&limit) {
        return Err(StoreError::InvalidInput);
    }
    i64::try_from(limit).map_err(StoreError::invalid_input)
}

/// Raw `applications` row.
#[derive(Debug)]
struct ApplicationRow {
    id: String,
    desired_json: String,
    generation: i64,
    delete_intent: i64,
    created_at_ms: i64,
    updated_at_ms: i64,
}

impl ApplicationRow {
    /// Deserializes the stored manifest, rejecting rows whose manifest ID
    /// disagrees with the row ID.
    fn decode(self) -> Result<StoredApplication, StoreError> {
        let application: ApplicationTemplate =
            serde_json::from_str(&self.desired_json).map_err(StoreError::corrupt)?;
        if application.id().as_str() != self.id {
            return Err(StoreError::Corrupt);
        }
        Ok(StoredApplication {
            application,
            generation: u64::try_from(self.generation).map_err(StoreError::corrupt)?,
            delete_intent: self.delete_intent != 0,
            created_at_ms: self.created_at_ms,
            updated_at_ms: self.updated_at_ms,
        })
    }
}

/// Raw `environments` row.
#[derive(Debug)]
struct EnvironmentRow {
    id: String,
    application_id: String,
    name: String,
    branch: Option<String>,
    pinned_commit: Option<String>,
    resolved_generation: Option<i64>,
    delete_intent: i64,
    created_at_ms: i64,
    updated_at_ms: i64,
}

impl EnvironmentRow {
    /// Converts raw columns into the environment view, reporting out-of-range
    /// values as corruption.
    fn decode(self) -> Result<EnvironmentView, StoreError> {
        Ok(EnvironmentView {
            id: EnvironmentId::parse(self.id).map_err(StoreError::corrupt)?,
            application_id: ApplicationId::parse(self.application_id)
                .map_err(StoreError::corrupt)?,
            name: EnvironmentName::parse(self.name).map_err(StoreError::corrupt)?,
            source: match self.branch {
                Some(branch) => EnvironmentSource::Branch(
                    TrackedBranch::new(branch, self.pinned_commit).map_err(StoreError::corrupt)?,
                ),
                None => EnvironmentSource::Saved,
            },
            resolved_generation: self
                .resolved_generation
                .map(u64::try_from)
                .transpose()
                .map_err(StoreError::corrupt)?,
            delete_intent: self.delete_intent != 0,
            created_at_ms: self.created_at_ms,
            updated_at_ms: self.updated_at_ms,
        })
    }
}

/// An environment joined with its application, as selected by full environment reads.
#[derive(Debug)]
struct StoredEnvironmentRow {
    id: String,
    application_id: String,
    name: String,
    branch: Option<String>,
    pinned_commit: Option<String>,
    manifest_json: Option<String>,
    resolved_json: Option<String>,
    resolved_generation: Option<i64>,
    delete_intent: i64,
    created_at_ms: i64,
    updated_at_ms: i64,
    desired_json: String,
    generation: i64,
    application_delete_intent: i64,
    application_created_at_ms: i64,
    application_updated_at_ms: i64,
}

impl StoredEnvironmentRow {
    /// Splits the joined row into its environment and application parts.
    fn decode(self) -> Result<StoredEnvironment, StoreError> {
        let application = ApplicationRow {
            id: self.application_id.clone(),
            desired_json: self.desired_json,
            generation: self.generation,
            delete_intent: self.application_delete_intent,
            created_at_ms: self.application_created_at_ms,
            updated_at_ms: self.application_updated_at_ms,
        }
        .decode()?;
        let environment = EnvironmentRow {
            id: self.id,
            application_id: self.application_id,
            name: self.name,
            branch: self.branch,
            pinned_commit: self.pinned_commit,
            resolved_generation: self.resolved_generation,
            delete_intent: self.delete_intent,
            created_at_ms: self.created_at_ms,
            updated_at_ms: self.updated_at_ms,
        }
        .decode()?;
        // Renames change display identity without rewriting fetched manifests.
        let fetched = self
            .manifest_json
            .as_deref()
            .map(serde_json::from_str::<ApplicationTemplate>)
            .transpose()
            .map_err(StoreError::corrupt)?
            .map(|fetched| fetched.with_name(application.application.metadata().name.clone()));
        Ok(StoredEnvironment {
            environment,
            application,
            fetched,
            resolved: self
                .resolved_json
                .as_deref()
                .map(serde_json::from_str)
                .transpose()
                .map_err(StoreError::corrupt)?,
        })
    }
}

#[cfg(test)]
mod observability_tests;

#[cfg(test)]
mod environment_tests;

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn every_committed_migration_reopens_after_a_later_migration_fails() {
        for committed in 0..=MIGRATIONS.len() {
            let directory = tempfile::tempdir().unwrap();
            let path = directory.path().join("migration.db");
            let options = SqliteConnectOptions::new()
                .filename(&path)
                .create_if_missing(true)
                .foreign_keys(true);
            let pool = SqlitePoolOptions::new()
                .max_connections(1)
                .connect_with(options)
                .await
                .unwrap();
            for (index, migration) in MIGRATIONS.iter().take(committed).enumerate() {
                Store::apply_migration(&pool, index + 1, migration)
                    .await
                    .unwrap();
            }
            assert!(
                Store::apply_migration(
                    &pool,
                    committed + 1,
                    "CREATE TABLE incomplete_migration(id INTEGER); INSERT INTO missing_table VALUES(1);",
                )
                .await
                .is_err()
            );
            let version: i64 = sqlx::query_scalar("PRAGMA user_version")
                .fetch_one(&pool)
                .await
                .unwrap();
            assert_eq!(usize::try_from(version).unwrap(), committed);
            let incomplete: i64 = sqlx::query_scalar(
                "SELECT COUNT(*) FROM sqlite_master WHERE name='incomplete_migration'",
            )
            .fetch_one(&pool)
            .await
            .unwrap();
            assert_eq!(incomplete, 0);
            let identity = if committed == 0 {
                None
            } else {
                let row = sqlx::query!(
                    "SELECT instance_id,schema_version FROM instance_metadata WHERE singleton=1"
                )
                .fetch_one(&pool)
                .await
                .unwrap();
                assert_eq!(row.schema_version, version);
                Some(row.instance_id)
            };
            pool.close().await;

            let reopened = Store::open(&path).await.unwrap();
            if let Some(identity) = identity {
                assert_eq!(reopened.instance_id(), identity);
            }
            reopened.pool.close().await;
        }
    }
}
