[package]
name = "piquelctl"
default-run = "piquelctl"
description = "Command-line client for piqueld"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
clap.workspace = true
piqueld-client.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
uuid.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
