[package]
name = "piquelctl"
default-run = "piquelctl"
description = "Command-line client for piqueld"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
piqueld-client.workspace = true

[lints]
workspace = true
