// Generated by Progenitor. Run `just generate`; do not edit.

// Progenitor emits mechanical patterns that intentionally trip style lints.
#![allow(clippy::all, clippy::pedantic, dead_code, private_interfaces)]

#[allow(unused_imports)]
pub use progenitor_client::{ByteStream, ClientInfo, Error, ResponseValue};
#[allow(unused_imports)]
use progenitor_client::{ClientHooks, OperationInfo, RequestBuilderExt, encode_path};
/// Types used as operation parameters and responses.
#[allow(clippy::all)]
pub mod types {
    /// Error types.
    pub mod error {
        /// Error from a `TryFrom` or `FromStr` implementation.
        pub struct ConversionError(::std::borrow::Cow<'static, str>);
        impl ::std::error::Error for ConversionError {}
        impl ::std::fmt::Display for ConversionError {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Display::fmt(&self.0, f)
            }
        }
        impl ::std::fmt::Debug for ConversionError {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Debug::fmt(&self.0, f)
            }
        }
        impl From<&'static str> for ConversionError {
            fn from(value: &'static str) -> Self {
                Self(value.into())
            }
        }
        impl From<String> for ConversionError {
            fn from(value: String) -> Self {
                Self(value.into())
            }
        }
    }
}
#[derive(Clone, Debug)]
/*Client for piqueld API

piqueld control-plane API. Mutation responses identify durable operations; named volumes are retained on deletion.

Version: v1*/
pub struct Client {
    pub(crate) baseurl: String,
    pub(crate) client: reqwest::Client,
    pub(crate) inner: crate::client::ClientState,
}
impl Client {
    /// Create a new client.
    ///
    /// `baseurl` is the base URL provided to the internal
    /// `reqwest::Client`, and should include a scheme and hostname,
    /// as well as port and a path stem if applicable.
    pub fn new(baseurl: &str, inner: crate::client::ClientState) -> Self {
        #[cfg(not(target_arch = "wasm32"))]
        let client = {
            let dur = ::std::time::Duration::from_secs(15u64);
            reqwest::ClientBuilder::new()
                .connect_timeout(dur)
                .timeout(dur)
        };
        #[cfg(target_arch = "wasm32")]
        let client = reqwest::ClientBuilder::new();
        Self::new_with_client(baseurl, client.build().unwrap(), inner)
    }
    /// Construct a new client with an existing `reqwest::Client`,
    /// allowing more control over its configuration.
    ///
    /// `baseurl` is the base URL provided to the internal
    /// `reqwest::Client`, and should include a scheme and hostname,
    /// as well as port and a path stem if applicable.
    pub fn new_with_client(
        baseurl: &str,
        client: reqwest::Client,
        inner: crate::client::ClientState,
    ) -> Self {
        Self {
            baseurl: baseurl.to_string(),
            client,
            inner,
        }
    }
}
impl ClientInfo<crate::client::ClientState> for Client {
    fn api_version() -> &'static str {
        "v1"
    }
    fn baseurl(&self) -> &str {
        self.baseurl.as_str()
    }
    fn client(&self) -> &reqwest::Client {
        &self.client
    }
    fn inner(&self) -> &crate::client::ClientState {
        &self.inner
    }
}
impl ClientHooks<crate::client::ClientState> for &Client {}
#[allow(clippy::all)]
impl Client {
    /*List applications

    Sends a `GET` request to `/api/v1/applications`

    */
    pub async fn list_applications<'a>(
        &'a self,
        cursor: Option<&'a str>,
        limit: Option<u32>,
    ) -> Result<
        ResponseValue<
            piqueld_core::api::Envelope<
                piqueld_core::api::Page<piqueld_core::api::ApplicationSummary>,
            >,
        >,
        Error<piqueld_core::api::ErrorBody>,
    > {
        let url = format!("{}/api/v1/applications", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .query(&progenitor_client::QueryParam::new("cursor", &cursor))
            .query(&progenitor_client::QueryParam::new("limit", &limit))
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "list_applications",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => crate::client::decode_response(response).await,
            400u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            500u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            503u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Apply an application manifest

    Sends a `POST` request to `/api/v1/applications/apply`

    Arguments:
    - `deploy`: Deploy the saved configuration; omission saves only.
    - `force`: Explicitly bypass revision and identity preconditions.
    - `idempotency_key`
    - `x_expected_application_id`: TOML only: inspected application identity. JSON uses `expected_application_id` in the request body.
    - `x_expected_generation`: TOML only: required unless forced; zero requires absence. JSON uses `expected_generation` in the request body.
    - `body`
    */
    pub async fn apply_application<'a>(
        &'a self,
        deploy: Option<bool>,
        force: Option<bool>,
        idempotency_key: Option<&'a str>,
        x_expected_application_id: Option<&'a str>,
        x_expected_generation: Option<u64>,
        body: &'a piqueld_core::api::ApplyApplicationRequest,
    ) -> Result<
        ResponseValue<piqueld_core::api::Envelope<piqueld_core::api::SavedApplication>>,
        Error<piqueld_core::api::ErrorBody>,
    > {
        let url = format!("{}/api/v1/applications/apply", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(4usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        if let Some(value) = idempotency_key {
            header_map.append("Idempotency-Key", value.to_string().try_into()?);
        }
        if let Some(value) = x_expected_application_id {
            header_map.append("X-Expected-Application-Id", value.to_string().try_into()?);
        }
        if let Some(value) = x_expected_generation {
            header_map.append("X-Expected-Generation", value.to_string().try_into()?);
        }
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .query(&progenitor_client::QueryParam::new("deploy", &deploy))
            .query(&progenitor_client::QueryParam::new("force", &force))
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "apply_application",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => crate::client::decode_response(response).await,
            202u16 => crate::client::decode_response(response).await,
            400u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            409u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            413u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            415u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            422u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            500u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            502u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            503u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Preview an application manifest

    Sends a `POST` request to `/api/v1/applications/plan`

    Arguments:
    - `x_expected_application_id`: TOML only: inspected application identity. JSON uses `expected_application_id` in the request body.
    - `x_expected_generation`: TOML only: inspected intent revision; zero requires absence. JSON uses `expected_generation` in the request body.
    - `body`
    */
    pub async fn plan_application<'a>(
        &'a self,
        x_expected_application_id: Option<&'a str>,
        x_expected_generation: Option<u64>,
        body: &'a piqueld_core::api::ApplyApplicationRequest,
    ) -> Result<
        ResponseValue<piqueld_core::api::Envelope<piqueld_core::api::PlanView>>,
        Error<piqueld_core::api::ErrorBody>,
    > {
        let url = format!("{}/api/v1/applications/plan", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(3usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        if let Some(value) = x_expected_application_id {
            header_map.append("X-Expected-Application-Id", value.to_string().try_into()?);
        }
        if let Some(value) = x_expected_generation {
            header_map.append("X-Expected-Generation", value.to_string().try_into()?);
        }
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "plan_application",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => crate::client::decode_response(response).await,
            400u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            409u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            413u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            415u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            422u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            500u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            502u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            503u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Get an application

    Sends a `GET` request to `/api/v1/applications/{id}`

    */
    pub async fn get_application<'a>(
        &'a self,
        id: &'a str,
    ) -> Result<
        ResponseValue<piqueld_core::api::Envelope<piqueld_core::api::ApplicationView>>,
        Error<piqueld_core::api::ErrorBody>,
    > {
        let url = format!(
            "{}/api/v1/applications/{}",
            self.baseurl,
            encode_path(&id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "get_application",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => crate::client::decode_response(response).await,
            400u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            404u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            500u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            503u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Delete services and networks, retaining volumes

    Sends a `DELETE` request to `/api/v1/applications/{id}`

    Arguments:
    - `id`
    - `expected_generation`: Current intent revision; optional for reconcile, required for deployment and deletion unless forced.
    - `force`: Explicitly bypass intent preconditions.
    - `idempotency_key`
    */
    pub async fn delete_application<'a>(
        &'a self,
        id: &'a str,
        expected_generation: Option<u64>,
        force: Option<bool>,
        idempotency_key: Option<&'a str>,
    ) -> Result<
        ResponseValue<piqueld_core::api::Envelope<piqueld_core::api::AcceptedOperation>>,
        Error<piqueld_core::api::ErrorBody>,
    > {
        let url = format!(
            "{}/api/v1/applications/{}",
            self.baseurl,
            encode_path(&id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(2usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        if let Some(value) = idempotency_key {
            header_map.append("Idempotency-Key", value.to_string().try_into()?);
        }
        #[allow(unused_mut)]
        let mut request = self
            .client
            .delete(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .query(&progenitor_client::QueryParam::new(
                "expected_generation",
                &expected_generation,
            ))
            .query(&progenitor_client::QueryParam::new("force", &force))
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "delete_application",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            202u16 => crate::client::decode_response(response).await,
            400u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            404u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            409u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            500u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            503u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Sends a `POST` request to `/api/v1/applications/{id}/deploy`

    Arguments:
    - `id`
    - `expected_generation`: Current intent revision; optional for reconcile, required for deployment and deletion unless forced.
    - `force`: Explicitly bypass intent preconditions.
    - `idempotency_key`
    */
    pub async fn deploy_application<'a>(
        &'a self,
        id: &'a str,
        expected_generation: Option<u64>,
        force: Option<bool>,
        idempotency_key: Option<&'a str>,
    ) -> Result<
        ResponseValue<piqueld_core::api::Envelope<piqueld_core::api::AcceptedOperation>>,
        Error<piqueld_core::api::ErrorBody>,
    > {
        let url = format!(
            "{}/api/v1/applications/{}/deploy",
            self.baseurl,
            encode_path(&id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(2usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        if let Some(value) = idempotency_key {
            header_map.append("Idempotency-Key", value.to_string().try_into()?);
        }
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .query(&progenitor_client::QueryParam::new(
                "expected_generation",
                &expected_generation,
            ))
            .query(&progenitor_client::QueryParam::new("force", &force))
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "deploy_application",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            202u16 => crate::client::decode_response(response).await,
            400u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            404u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            409u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            500u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            503u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Sends a `GET` request to `/api/v1/applications/{id}/deployments`

    */
    pub async fn list_deployments<'a>(
        &'a self,
        id: &'a str,
        cursor: Option<&'a str>,
    ) -> Result<
        ResponseValue<
            piqueld_core::api::Envelope<piqueld_core::api::Page<piqueld_core::api::DeploymentView>>,
        >,
        Error<piqueld_core::api::ErrorBody>,
    > {
        let url = format!(
            "{}/api/v1/applications/{}/deployments",
            self.baseurl,
            encode_path(&id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .query(&progenitor_client::QueryParam::new("cursor", &cursor))
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "list_deployments",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => crate::client::decode_response(response).await,
            400u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            404u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            500u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Sends a `GET` request to `/api/v1/applications/{id}/deployments/{deployment}/attempts`

    */
    pub async fn list_deployment_attempts<'a>(
        &'a self,
        id: &'a str,
        deployment: &'a str,
        cursor: Option<&'a str>,
    ) -> Result<
        ResponseValue<
            piqueld_core::api::Envelope<piqueld_core::api::Page<piqueld_core::Operation>>,
        >,
        Error<piqueld_core::api::ErrorBody>,
    > {
        let url = format!(
            "{}/api/v1/applications/{}/deployments/{}/attempts",
            self.baseurl,
            encode_path(&id.to_string()),
            encode_path(&deployment.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .query(&progenitor_client::QueryParam::new("cursor", &cursor))
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "list_deployment_attempts",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => crate::client::decode_response(response).await,
            400u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            404u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            500u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Get desired and observed application state

    Sends a `GET` request to `/api/v1/applications/{id}/detail`

    */
    pub async fn get_application_detail<'a>(
        &'a self,
        id: &'a str,
    ) -> Result<
        ResponseValue<piqueld_core::api::Envelope<piqueld_core::api::ApplicationDetailView>>,
        Error<piqueld_core::api::ErrorBody>,
    > {
        let url = format!(
            "{}/api/v1/applications/{}/detail",
            self.baseurl,
            encode_path(&id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "get_application_detail",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => crate::client::decode_response(response).await,
            400u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            404u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            500u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            502u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            503u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Sends a `GET` request to `/api/v1/applications/{id}/logs`

    */
    pub async fn application_logs<'a>(
        &'a self,
        id: &'a str,
        service: Option<&'a str>,
        since_seconds: Option<u32>,
        tail: Option<u32>,
    ) -> Result<
        ResponseValue<piqueld_core::api::Envelope<piqueld_core::api::ApplicationLogs>>,
        Error<piqueld_core::api::ErrorBody>,
    > {
        let url = format!(
            "{}/api/v1/applications/{}/logs",
            self.baseurl,
            encode_path(&id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .query(&progenitor_client::QueryParam::new("service", &service))
            .query(&progenitor_client::QueryParam::new(
                "since_seconds",
                &since_seconds,
            ))
            .query(&progenitor_client::QueryParam::new("tail", &tail))
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "application_logs",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => crate::client::decode_response(response).await,
            400u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            404u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            502u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            503u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Download only saved configuration; runtime availability is irrelevant

    Sends a `GET` request to `/api/v1/applications/{id}/manifest`

    */
    pub async fn download_application_manifest<'a>(
        &'a self,
        id: &'a str,
    ) -> Result<ResponseValue<ByteStream>, Error<piqueld_core::api::ErrorBody>> {
        let url = format!(
            "{}/api/v1/applications/{}/manifest",
            self.baseurl,
            encode_path(&id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self.client.get(url).headers(header_map).build()?;
        let info = OperationInfo {
            operation_id: "download_application_manifest",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => Ok(ResponseValue::stream(response)),
            400u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            404u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            500u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            503u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Sends a `POST` request to `/api/v1/applications/{id}/reconcile`

    Arguments:
    - `id`
    - `expected_generation`: Current intent revision; optional for reconcile, required for deployment and deletion unless forced.
    - `force`: Explicitly bypass intent preconditions.
    - `idempotency_key`
    */
    pub async fn reconcile_application<'a>(
        &'a self,
        id: &'a str,
        expected_generation: Option<u64>,
        force: Option<bool>,
        idempotency_key: Option<&'a str>,
    ) -> Result<
        ResponseValue<piqueld_core::api::Envelope<piqueld_core::api::AcceptedOperation>>,
        Error<piqueld_core::api::ErrorBody>,
    > {
        let url = format!(
            "{}/api/v1/applications/{}/reconcile",
            self.baseurl,
            encode_path(&id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(2usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        if let Some(value) = idempotency_key {
            header_map.append("Idempotency-Key", value.to_string().try_into()?);
        }
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .query(&progenitor_client::QueryParam::new(
                "expected_generation",
                &expected_generation,
            ))
            .query(&progenitor_client::QueryParam::new("force", &force))
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "reconcile_application",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            202u16 => crate::client::decode_response(response).await,
            400u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            404u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            409u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            500u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            503u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Sends a `POST` request to `/api/v1/applications/{id}/rename`

    Arguments:
    - `id`
    - `force`: Explicitly bypass the intent revision precondition and, for apply, the name-based identity precondition. Name availability is always enforced.
    - `idempotency_key`
    - `body`
    */
    pub async fn rename_application<'a>(
        &'a self,
        id: &'a str,
        force: Option<bool>,
        idempotency_key: Option<&'a str>,
        body: &'a piqueld_core::api::RenameApplicationRequest,
    ) -> Result<
        ResponseValue<piqueld_core::api::Envelope<piqueld_core::api::RenamedApplication>>,
        Error<piqueld_core::api::ErrorBody>,
    > {
        let url = format!(
            "{}/api/v1/applications/{}/rename",
            self.baseurl,
            encode_path(&id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(2usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        if let Some(value) = idempotency_key {
            header_map.append("Idempotency-Key", value.to_string().try_into()?);
        }
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .query(&progenitor_client::QueryParam::new("force", &force))
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "rename_application",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => crate::client::decode_response(response).await,
            400u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            404u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            409u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            500u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            503u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Get application status

    Sends a `GET` request to `/api/v1/applications/{id}/status`

    */
    pub async fn application_status<'a>(
        &'a self,
        id: &'a str,
    ) -> Result<
        ResponseValue<piqueld_core::api::Envelope<piqueld_core::api::ApplicationStatusView>>,
        Error<piqueld_core::api::ErrorBody>,
    > {
        let url = format!(
            "{}/api/v1/applications/{}/status",
            self.baseurl,
            encode_path(&id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "application_status",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => crate::client::decode_response(response).await,
            400u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            404u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            500u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            503u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Sends a `GET` request to `/api/v1/builds`

    */
    pub async fn list_builds<'a>(
        &'a self,
        application_id: Option<&'a str>,
        cursor: Option<&'a str>,
        limit: Option<i64>,
    ) -> Result<
        ResponseValue<
            piqueld_core::api::Envelope<piqueld_core::api::Page<piqueld_core::api::BuildRecord>>,
        >,
        Error<piqueld_core::api::ErrorBody>,
    > {
        let url = format!("{}/api/v1/builds", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .query(&progenitor_client::QueryParam::new(
                "application_id",
                &application_id,
            ))
            .query(&progenitor_client::QueryParam::new("cursor", &cursor))
            .query(&progenitor_client::QueryParam::new("limit", &limit))
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "list_builds",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => crate::client::decode_response(response).await,
            400u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            503u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Sends a `GET` request to `/api/v1/builds/{id}/logs`

    */
    pub async fn build_logs<'a>(
        &'a self,
        id: i64,
        offset: Option<i64>,
    ) -> Result<
        ResponseValue<piqueld_core::api::Envelope<piqueld_core::api::BuildLogPage>>,
        Error<piqueld_core::api::ErrorBody>,
    > {
        let url = format!(
            "{}/api/v1/builds/{}/logs",
            self.baseurl,
            encode_path(&id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .query(&progenitor_client::QueryParam::new("offset", &offset))
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "build_logs",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => crate::client::decode_response(response).await,
            400u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            404u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            503u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Sends a `GET` request to `/api/v1/events`

    */
    pub async fn list_events<'a>(
        &'a self,
        application_id: Option<&'a str>,
        cursor: Option<&'a str>,
        limit: Option<i64>,
    ) -> Result<
        ResponseValue<piqueld_core::api::Envelope<piqueld_core::api::Page<piqueld_core::Event>>>,
        Error<piqueld_core::api::ErrorBody>,
    > {
        let url = format!("{}/api/v1/events", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .query(&progenitor_client::QueryParam::new(
                "application_id",
                &application_id,
            ))
            .query(&progenitor_client::QueryParam::new("cursor", &cursor))
            .query(&progenitor_client::QueryParam::new("limit", &limit))
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "list_events",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => crate::client::decode_response(response).await,
            400u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            503u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Get the `OpenAPI` document

    Sends a `GET` request to `/api/v1/openapi.json`

    */
    pub async fn open_api_document<'a>(&'a self) -> Result<ResponseValue<ByteStream>, Error<()>> {
        let url = format!("{}/api/v1/openapi.json", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self.client.get(url).headers(header_map).build()?;
        let info = OperationInfo {
            operation_id: "open_api_document",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => Ok(ResponseValue::stream(response)),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Get an operation

    Sends a `GET` request to `/api/v1/operations/{id}`

    */
    pub async fn get_operation<'a>(
        &'a self,
        id: &'a str,
    ) -> Result<
        ResponseValue<piqueld_core::api::Envelope<piqueld_core::Operation>>,
        Error<piqueld_core::api::ErrorBody>,
    > {
        let url = format!(
            "{}/api/v1/operations/{}",
            self.baseurl,
            encode_path(&id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "get_operation",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => crate::client::decode_response(response).await,
            404u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            500u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            503u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Sends a `GET` request to `/api/v1/system/configuration`

    */
    pub async fn system_configuration<'a>(
        &'a self,
    ) -> Result<
        ResponseValue<piqueld_core::api::Envelope<piqueld_core::api::HostConfiguration>>,
        Error<piqueld_core::api::ErrorBody>,
    > {
        let url = format!("{}/api/v1/system/configuration", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "system_configuration",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => crate::client::decode_response(response).await,
            503u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Sends a `GET` request to `/api/v1/system/readiness`

    */
    pub async fn system_readiness<'a>(
        &'a self,
    ) -> Result<
        ResponseValue<piqueld_core::api::Envelope<piqueld_core::api::ReadinessStatus>>,
        Error<piqueld_core::api::Envelope<piqueld_core::api::ReadinessStatus>>,
    > {
        let url = format!("{}/api/v1/system/readiness", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "system_readiness",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => crate::client::decode_response(response).await,
            503u16 => Err(Error::ErrorResponse(
                crate::client::decode_response(response).await?,
            )),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /*Get daemon status

    Sends a `GET` request to `/api/v1/system/status`

    */
    pub async fn system_status<'a>(
        &'a self,
    ) -> Result<
        ResponseValue<piqueld_core::api::Envelope<piqueld_core::api::SystemStatus>>,
        Error<()>,
    > {
        let url = format!("{}/api/v1/system/status", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .header(
                ::reqwest::header::ACCEPT,
                ::reqwest::header::HeaderValue::from_static("application/json"),
            )
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "system_status",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => crate::client::decode_response(response).await,
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
}
/// Items consumers will typically use such as the Client.
pub mod prelude {
    #[allow(unused_imports)]
    pub use super::Client;
}
