// Generated by OpenAPI Generator. Run `just generate-client`; do not edit.

// A uniform request pipeline keeps the template independent of parameter count.
#![allow(clippy::let_and_return)]

use crate::client::{GeneratedRequest, path_segment};
use crate::{Client, ClientError};

/// Existing Rust contracts used by the generated operations.
pub mod models {
    /// Shared wire contract.
    pub type EnvelopeAcceptedOperation = crate::Envelope<piqueld_core::api::AcceptedOperation>;
    /// Shared wire contract.
    pub type EnvelopeApplicationDetailView =
        crate::Envelope<piqueld_core::api::ApplicationDetailView>;
    /// Shared wire contract.
    pub type EnvelopeApplicationLogs = crate::Envelope<piqueld_core::api::ApplicationLogs>;
    /// Shared wire contract.
    pub type EnvelopeApplicationStatusView =
        crate::Envelope<piqueld_core::api::ApplicationStatusView>;
    /// Shared wire contract.
    pub type EnvelopeApplicationView = crate::Envelope<piqueld_core::api::ApplicationView>;
    /// Shared wire contract.
    pub type EnvelopeBuildLogPage = crate::Envelope<piqueld_core::api::BuildLogPage>;
    /// Shared wire contract.
    pub type EnvelopeHostConfiguration = crate::Envelope<piqueld_core::api::HostConfiguration>;
    /// Shared wire contract.
    pub type EnvelopeOperation = crate::Envelope<piqueld_core::Operation>;
    /// Shared wire contract.
    pub type EnvelopePageApplicationSummary =
        crate::Envelope<crate::Page<piqueld_core::api::ApplicationSummary>>;
    /// Shared wire contract.
    pub type EnvelopePageBuildRecord = crate::Envelope<crate::Page<piqueld_core::api::BuildRecord>>;
    /// Shared wire contract.
    pub type EnvelopePageDeploymentView =
        crate::Envelope<crate::Page<piqueld_core::api::DeploymentView>>;
    /// Shared wire contract.
    pub type EnvelopePageEvent = crate::Envelope<crate::Page<piqueld_core::Event>>;
    /// Shared wire contract.
    pub type EnvelopePageOperation = crate::Envelope<crate::Page<piqueld_core::Operation>>;
    /// Shared wire contract.
    pub type EnvelopePlanView = crate::Envelope<piqueld_core::api::PlanView>;
    /// Shared wire contract.
    pub type EnvelopeReadinessStatus = crate::Envelope<piqueld_core::api::ReadinessStatus>;
    /// Shared wire contract.
    pub type EnvelopeRenamedApplication = crate::Envelope<piqueld_core::api::RenamedApplication>;
    /// Shared wire contract.
    pub type EnvelopeSavedApplication = crate::Envelope<piqueld_core::api::SavedApplication>;
    /// Shared wire contract.
    pub type EnvelopeSystemStatus = crate::Envelope<piqueld_core::api::SystemStatus>;
    /// Shared wire contract.
    pub type ApplyApplicationRequest = piqueld_core::api::ApplyApplicationRequest;
    /// Shared wire contract.
    pub type RenameApplicationRequest = piqueld_core::api::RenameApplicationRequest;
    /// Shared wire contract.
    pub type ErrorBody = piqueld_core::api::ErrorBody;
}

/// `applicationLogs`
#[derive(Clone, Debug, Default)]
pub struct ApplicationLogs {
    /// `id`
    pub id: String,
    /// `service`
    pub service: Option<String>,
    /// `tail`
    pub tail: Option<u32>,
    /// `since_seconds`
    pub since_seconds: Option<u32>,
}

impl ApplicationLogs {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    pub(crate) fn request(&self) -> GeneratedRequest {
        let path = format!(
            "/api/v1/applications/{id}/logs",
            id = path_segment(&self.id)
        );
        let mut request = GeneratedRequest::new(http::Method::GET, path);
        if let Some(value) = &self.service {
            request.query("service", value);
        }
        if let Some(value) = &self.tail {
            request.query("tail", value);
        }
        if let Some(value) = &self.since_seconds {
            request.query("since_seconds", value);
        }
        request
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(
        &self,
        client: &Client,
    ) -> Result<models::EnvelopeApplicationLogs, ClientError> {
        self.request().send_json(client, &[]).await
    }
}
/// Get application status
#[derive(Clone, Debug, Default)]
pub struct ApplicationStatus {
    /// `id`
    pub id: String,
}

impl ApplicationStatus {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    pub(crate) fn request(&self) -> GeneratedRequest {
        let path = format!(
            "/api/v1/applications/{id}/status",
            id = path_segment(&self.id)
        );
        let request = GeneratedRequest::new(http::Method::GET, path);
        request
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(
        &self,
        client: &Client,
    ) -> Result<models::EnvelopeApplicationStatusView, ClientError> {
        self.request().send_json(client, &[]).await
    }
}
/// Apply an application manifest
#[derive(Clone, Debug, Default)]
pub struct ApplyApplication {
    /// `force`: Explicitly bypass revision and identity preconditions.
    pub force: Option<bool>,
    /// `deploy`: Deploy the saved configuration; omission saves only.
    pub deploy: Option<bool>,
    /// `X-Expected-Generation`: TOML only: required unless forced; zero requires absence. JSON uses `expected_generation` in the request body.
    pub x_expected_generation: Option<u64>,
    /// `X-Expected-Application-Id`: TOML only: inspected application identity. JSON uses `expected_application_id` in the request body.
    pub x_expected_application_id: Option<String>,
    /// `Idempotency-Key`
    pub idempotency_key: Option<String>,
}

/// Supported request representations for [`ApplyApplication`].
#[derive(Clone, Copy, Debug)]
pub enum ApplyApplicationBody<'a> {
    /// `application/json` request body.
    ApplicationJson(&'a models::ApplyApplicationRequest),
    /// `application/toml` request body.
    ApplicationToml(&'a str),
    /// `text/toml` request body.
    TextToml(&'a str),
}

impl ApplyApplication {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    pub(crate) fn request(
        &self,
        body: ApplyApplicationBody<'_>,
    ) -> Result<GeneratedRequest, ClientError> {
        let path = "/api/v1/applications/apply".to_owned();
        let mut request = GeneratedRequest::new(http::Method::POST, path);
        if let Some(value) = &self.force {
            request.query("force", value);
        }
        if let Some(value) = &self.deploy {
            request.query("deploy", value);
        }
        if let Some(value) = &self.x_expected_generation {
            request.header("X-Expected-Generation", value);
        }
        if let Some(value) = &self.x_expected_application_id {
            request.header("X-Expected-Application-Id", value);
        }
        if let Some(value) = &self.idempotency_key {
            request.header("Idempotency-Key", value);
        }
        let request = match body {
            ApplyApplicationBody::ApplicationJson(body) => {
                request.json("application/json", body)?
            }
            ApplyApplicationBody::ApplicationToml(body) => request.text("application/toml", body),
            ApplyApplicationBody::TextToml(body) => request.text("text/toml", body),
        };
        Ok(request)
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(
        &self,
        client: &Client,
        body: ApplyApplicationBody<'_>,
    ) -> Result<models::EnvelopeSavedApplication, ClientError> {
        self.request(body)?.send_json(client, &[]).await
    }
}
/// `buildLogs`
#[derive(Clone, Debug, Default)]
pub struct BuildLogs {
    /// `id`
    pub id: i64,
    /// `offset`
    pub offset: Option<i64>,
}

impl BuildLogs {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    pub(crate) fn request(&self) -> GeneratedRequest {
        let path = format!(
            "/api/v1/builds/{id}/logs",
            id = path_segment(&self.id.to_string())
        );
        let mut request = GeneratedRequest::new(http::Method::GET, path);
        if let Some(value) = &self.offset {
            request.query("offset", value);
        }
        request
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(&self, client: &Client) -> Result<models::EnvelopeBuildLogPage, ClientError> {
        self.request().send_json(client, &[]).await
    }
}
/// Delete services and networks, retaining volumes
#[derive(Clone, Debug, Default)]
pub struct DeleteApplication {
    /// `id`
    pub id: String,
    /// `expected_generation`: Current intent revision; optional for reconcile, required for deployment and deletion unless forced.
    pub expected_generation: Option<u64>,
    /// `force`: Explicitly bypass intent preconditions.
    pub force: Option<bool>,
    /// `Idempotency-Key`
    pub idempotency_key: Option<String>,
}

impl DeleteApplication {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    pub(crate) fn request(&self) -> GeneratedRequest {
        let path = format!("/api/v1/applications/{id}", id = path_segment(&self.id));
        let mut request = GeneratedRequest::new(http::Method::DELETE, path);
        if let Some(value) = &self.expected_generation {
            request.query("expected_generation", value);
        }
        if let Some(value) = &self.force {
            request.query("force", value);
        }
        if let Some(value) = &self.idempotency_key {
            request.header("Idempotency-Key", value);
        }
        request
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(
        &self,
        client: &Client,
    ) -> Result<models::EnvelopeAcceptedOperation, ClientError> {
        self.request().send_json(client, &[]).await
    }
}
/// `deployApplication`
#[derive(Clone, Debug, Default)]
pub struct DeployApplication {
    /// `id`
    pub id: String,
    /// `expected_generation`: Current intent revision; optional for reconcile, required for deployment and deletion unless forced.
    pub expected_generation: Option<u64>,
    /// `force`: Explicitly bypass intent preconditions.
    pub force: Option<bool>,
    /// `Idempotency-Key`
    pub idempotency_key: Option<String>,
}

impl DeployApplication {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    pub(crate) fn request(&self) -> GeneratedRequest {
        let path = format!(
            "/api/v1/applications/{id}/deploy",
            id = path_segment(&self.id)
        );
        let mut request = GeneratedRequest::new(http::Method::POST, path);
        if let Some(value) = &self.expected_generation {
            request.query("expected_generation", value);
        }
        if let Some(value) = &self.force {
            request.query("force", value);
        }
        if let Some(value) = &self.idempotency_key {
            request.header("Idempotency-Key", value);
        }
        request
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(
        &self,
        client: &Client,
    ) -> Result<models::EnvelopeAcceptedOperation, ClientError> {
        self.request().send_json(client, &[]).await
    }
}
/// Download only saved configuration; runtime availability is irrelevant.
#[derive(Clone, Debug, Default)]
pub struct DownloadApplicationManifest {
    /// `id`
    pub id: String,
}

impl DownloadApplicationManifest {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    pub(crate) fn request(&self) -> GeneratedRequest {
        let path = format!(
            "/api/v1/applications/{id}/manifest",
            id = path_segment(&self.id)
        );
        let request = GeneratedRequest::new(http::Method::GET, path);
        request
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(&self, client: &Client) -> Result<String, ClientError> {
        self.request().send_text(client, &[]).await
    }
}
/// Get an application
#[derive(Clone, Debug, Default)]
pub struct GetApplication {
    /// `id`
    pub id: String,
}

impl GetApplication {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    pub(crate) fn request(&self) -> GeneratedRequest {
        let path = format!("/api/v1/applications/{id}", id = path_segment(&self.id));
        let request = GeneratedRequest::new(http::Method::GET, path);
        request
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(
        &self,
        client: &Client,
    ) -> Result<models::EnvelopeApplicationView, ClientError> {
        self.request().send_json(client, &[]).await
    }
}
/// Get desired and observed application state
#[derive(Clone, Debug, Default)]
pub struct GetApplicationDetail {
    /// `id`
    pub id: String,
}

impl GetApplicationDetail {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    pub(crate) fn request(&self) -> GeneratedRequest {
        let path = format!(
            "/api/v1/applications/{id}/detail",
            id = path_segment(&self.id)
        );
        let request = GeneratedRequest::new(http::Method::GET, path);
        request
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(
        &self,
        client: &Client,
    ) -> Result<models::EnvelopeApplicationDetailView, ClientError> {
        self.request().send_json(client, &[]).await
    }
}
/// Get an operation
#[derive(Clone, Debug, Default)]
pub struct GetOperation {
    /// `id`
    pub id: String,
}

impl GetOperation {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    pub(crate) fn request(&self) -> GeneratedRequest {
        let path = format!("/api/v1/operations/{id}", id = path_segment(&self.id));
        let request = GeneratedRequest::new(http::Method::GET, path);
        request
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(&self, client: &Client) -> Result<models::EnvelopeOperation, ClientError> {
        self.request().send_json(client, &[]).await
    }
}
/// List applications
#[derive(Clone, Debug, Default)]
pub struct ListApplications {
    /// `cursor`
    pub cursor: Option<String>,
    /// `limit`
    pub limit: Option<u32>,
}

impl ListApplications {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    pub(crate) fn request(&self) -> GeneratedRequest {
        let path = "/api/v1/applications".to_owned();
        let mut request = GeneratedRequest::new(http::Method::GET, path);
        if let Some(value) = &self.cursor {
            request.query("cursor", value);
        }
        if let Some(value) = &self.limit {
            request.query("limit", value);
        }
        request
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(
        &self,
        client: &Client,
    ) -> Result<models::EnvelopePageApplicationSummary, ClientError> {
        self.request().send_json(client, &[]).await
    }
}
/// `listBuilds`
#[derive(Clone, Debug, Default)]
pub struct ListBuilds {
    /// `application_id`
    pub application_id: Option<String>,
    /// `cursor`
    pub cursor: Option<String>,
    /// `limit`
    pub limit: Option<u32>,
}

impl ListBuilds {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    pub(crate) fn request(&self) -> GeneratedRequest {
        let path = "/api/v1/builds".to_owned();
        let mut request = GeneratedRequest::new(http::Method::GET, path);
        if let Some(value) = &self.application_id {
            request.query("application_id", value);
        }
        if let Some(value) = &self.cursor {
            request.query("cursor", value);
        }
        if let Some(value) = &self.limit {
            request.query("limit", value);
        }
        request
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(
        &self,
        client: &Client,
    ) -> Result<models::EnvelopePageBuildRecord, ClientError> {
        self.request().send_json(client, &[]).await
    }
}
/// `listDeploymentAttempts`
#[derive(Clone, Debug, Default)]
pub struct ListDeploymentAttempts {
    /// `id`
    pub id: String,
    /// `deployment`
    pub deployment: String,
    /// `cursor`
    pub cursor: Option<String>,
}

impl ListDeploymentAttempts {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    pub(crate) fn request(&self) -> GeneratedRequest {
        let path = format!(
            "/api/v1/applications/{id}/deployments/{deployment}/attempts",
            id = path_segment(&self.id),
            deployment = path_segment(&self.deployment)
        );
        let mut request = GeneratedRequest::new(http::Method::GET, path);
        if let Some(value) = &self.cursor {
            request.query("cursor", value);
        }
        request
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(
        &self,
        client: &Client,
    ) -> Result<models::EnvelopePageOperation, ClientError> {
        self.request().send_json(client, &[]).await
    }
}
/// `listDeployments`
#[derive(Clone, Debug, Default)]
pub struct ListDeployments {
    /// `id`
    pub id: String,
    /// `cursor`
    pub cursor: Option<String>,
}

impl ListDeployments {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    pub(crate) fn request(&self) -> GeneratedRequest {
        let path = format!(
            "/api/v1/applications/{id}/deployments",
            id = path_segment(&self.id)
        );
        let mut request = GeneratedRequest::new(http::Method::GET, path);
        if let Some(value) = &self.cursor {
            request.query("cursor", value);
        }
        request
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(
        &self,
        client: &Client,
    ) -> Result<models::EnvelopePageDeploymentView, ClientError> {
        self.request().send_json(client, &[]).await
    }
}
/// `listEvents`
#[derive(Clone, Debug, Default)]
pub struct ListEvents {
    /// `application_id`
    pub application_id: Option<String>,
    /// `cursor`
    pub cursor: Option<String>,
    /// `limit`
    pub limit: Option<u32>,
}

impl ListEvents {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    pub(crate) fn request(&self) -> GeneratedRequest {
        let path = "/api/v1/events".to_owned();
        let mut request = GeneratedRequest::new(http::Method::GET, path);
        if let Some(value) = &self.application_id {
            request.query("application_id", value);
        }
        if let Some(value) = &self.cursor {
            request.query("cursor", value);
        }
        if let Some(value) = &self.limit {
            request.query("limit", value);
        }
        request
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(&self, client: &Client) -> Result<models::EnvelopePageEvent, ClientError> {
        self.request().send_json(client, &[]).await
    }
}
/// Get the `OpenAPI` document
#[derive(Clone, Debug, Default)]
pub struct OpenApiDocument {}

impl OpenApiDocument {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    // Keep the same request interface for operations with and without parameters.
    #[allow(clippy::unused_self)]
    pub(crate) fn request(&self) -> GeneratedRequest {
        let path = "/api/v1/openapi.json".to_owned();
        let request = GeneratedRequest::new(http::Method::GET, path);
        request
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(&self, client: &Client) -> Result<serde_json::Value, ClientError> {
        self.request().send_json(client, &[]).await
    }
}
/// Preview an application manifest
#[derive(Clone, Debug, Default)]
pub struct PlanApplication {
    /// `X-Expected-Generation`: TOML only: inspected intent revision; zero requires absence. JSON uses `expected_generation` in the request body.
    pub x_expected_generation: Option<u64>,
    /// `X-Expected-Application-Id`: TOML only: inspected application identity. JSON uses `expected_application_id` in the request body.
    pub x_expected_application_id: Option<String>,
}

/// Supported request representations for [`PlanApplication`].
#[derive(Clone, Copy, Debug)]
pub enum PlanApplicationBody<'a> {
    /// `application/json` request body.
    ApplicationJson(&'a models::ApplyApplicationRequest),
    /// `application/toml` request body.
    ApplicationToml(&'a str),
    /// `text/toml` request body.
    TextToml(&'a str),
}

impl PlanApplication {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    pub(crate) fn request(
        &self,
        body: PlanApplicationBody<'_>,
    ) -> Result<GeneratedRequest, ClientError> {
        let path = "/api/v1/applications/plan".to_owned();
        let mut request = GeneratedRequest::new(http::Method::POST, path);
        if let Some(value) = &self.x_expected_generation {
            request.header("X-Expected-Generation", value);
        }
        if let Some(value) = &self.x_expected_application_id {
            request.header("X-Expected-Application-Id", value);
        }
        let request = match body {
            PlanApplicationBody::ApplicationJson(body) => request.json("application/json", body)?,
            PlanApplicationBody::ApplicationToml(body) => request.text("application/toml", body),
            PlanApplicationBody::TextToml(body) => request.text("text/toml", body),
        };
        Ok(request)
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(
        &self,
        client: &Client,
        body: PlanApplicationBody<'_>,
    ) -> Result<models::EnvelopePlanView, ClientError> {
        self.request(body)?.send_json(client, &[]).await
    }
}
/// `reconcileApplication`
#[derive(Clone, Debug, Default)]
pub struct ReconcileApplication {
    /// `id`
    pub id: String,
    /// `expected_generation`: Current intent revision; optional for reconcile, required for deployment and deletion unless forced.
    pub expected_generation: Option<u64>,
    /// `force`: Explicitly bypass intent preconditions.
    pub force: Option<bool>,
    /// `Idempotency-Key`
    pub idempotency_key: Option<String>,
}

impl ReconcileApplication {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    pub(crate) fn request(&self) -> GeneratedRequest {
        let path = format!(
            "/api/v1/applications/{id}/reconcile",
            id = path_segment(&self.id)
        );
        let mut request = GeneratedRequest::new(http::Method::POST, path);
        if let Some(value) = &self.expected_generation {
            request.query("expected_generation", value);
        }
        if let Some(value) = &self.force {
            request.query("force", value);
        }
        if let Some(value) = &self.idempotency_key {
            request.header("Idempotency-Key", value);
        }
        request
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(
        &self,
        client: &Client,
    ) -> Result<models::EnvelopeAcceptedOperation, ClientError> {
        self.request().send_json(client, &[]).await
    }
}
/// `renameApplication`
#[derive(Clone, Debug, Default)]
pub struct RenameApplication {
    /// `id`
    pub id: String,
    /// `force`: Explicitly bypass the intent revision precondition and, for apply, the name-based identity precondition. Name availability is always enforced.
    pub force: Option<bool>,
    /// `Idempotency-Key`
    pub idempotency_key: Option<String>,
}

/// Supported request representations for [`RenameApplication`].
#[derive(Clone, Copy, Debug)]
pub enum RenameApplicationBody<'a> {
    /// `application/json` request body.
    ApplicationJson(&'a models::RenameApplicationRequest),
}

impl RenameApplication {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    pub(crate) fn request(
        &self,
        body: RenameApplicationBody<'_>,
    ) -> Result<GeneratedRequest, ClientError> {
        let path = format!(
            "/api/v1/applications/{id}/rename",
            id = path_segment(&self.id)
        );
        let mut request = GeneratedRequest::new(http::Method::POST, path);
        if let Some(value) = &self.force {
            request.query("force", value);
        }
        if let Some(value) = &self.idempotency_key {
            request.header("Idempotency-Key", value);
        }
        let request = match body {
            RenameApplicationBody::ApplicationJson(body) => {
                request.json("application/json", body)?
            }
        };
        Ok(request)
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(
        &self,
        client: &Client,
        body: RenameApplicationBody<'_>,
    ) -> Result<models::EnvelopeRenamedApplication, ClientError> {
        self.request(body)?.send_json(client, &[]).await
    }
}
/// `systemConfiguration`
#[derive(Clone, Debug, Default)]
pub struct SystemConfiguration {}

impl SystemConfiguration {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    // Keep the same request interface for operations with and without parameters.
    #[allow(clippy::unused_self)]
    pub(crate) fn request(&self) -> GeneratedRequest {
        let path = "/api/v1/system/configuration".to_owned();
        let request = GeneratedRequest::new(http::Method::GET, path);
        request
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(
        &self,
        client: &Client,
    ) -> Result<models::EnvelopeHostConfiguration, ClientError> {
        self.request().send_json(client, &[]).await
    }
}
/// `systemReadiness`
#[derive(Clone, Debug, Default)]
pub struct SystemReadiness {}

impl SystemReadiness {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    // Keep the same request interface for operations with and without parameters.
    #[allow(clippy::unused_self)]
    pub(crate) fn request(&self) -> GeneratedRequest {
        let path = "/api/v1/system/readiness".to_owned();
        let request = GeneratedRequest::new(http::Method::GET, path);
        request
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(
        &self,
        client: &Client,
    ) -> Result<models::EnvelopeReadinessStatus, ClientError> {
        self.request().send_json(client, &[]).await
    }
}
/// Get daemon status
#[derive(Clone, Debug, Default)]
pub struct SystemStatus {}

impl SystemStatus {
    /// Builds the documented request for the shared native/browser transport.
    /// # Errors
    /// Returns an error if the request body cannot be serialized.
    // Keep the same request interface for operations with and without parameters.
    #[allow(clippy::unused_self)]
    pub(crate) fn request(&self) -> GeneratedRequest {
        let path = "/api/v1/system/status".to_owned();
        let request = GeneratedRequest::new(http::Method::GET, path);
        request
    }

    /// Sends the request and decodes its documented response.
    /// # Errors
    /// Returns request construction, transport, API, or decoding errors.
    pub async fn send(&self, client: &Client) -> Result<models::EnvelopeSystemStatus, ClientError> {
        self.request().send_json(client, &[]).await
    }
}
