#!/usr/bin/env bash
# Runs one isolated development instance per worktree: its own configuration,
# data and runtime directories, port, and Docker engine, so worktrees never
# share state. See docs/development.md.
#
# Usage: scripts/dev.sh [COMMAND]
#   run          watch the sources and rebuild and restart the daemon (default)
#   start        run in the background, then wait until ready
#   wait [SECS]  wait until the current sources are built and serving
#   status       print the instance's state, URL, and files
#   stop         stop the daemon and the watcher
#   clean        stop, then delete the instance's Docker engine and state
#   prune        clean the instances of worktrees that no longer exist
#   config       write piqueld.local.toml unless it exists (--force replaces it)
#   ctl ARGS     run this worktree's piquelctl against the instance
#   serve        (run by the watcher) build, then exec the daemon
set -Eeuo pipefail

root=$(git rev-parse --show-toplevel)
cd "$root"
# shellcheck source=scripts/dind.sh
source scripts/dind.sh

config_file=piqueld.local.toml
# Changes to these restart the daemon; `wait` treats newer files as unbuilt.
watched=(apps/piqueld apps/piqueld-ui crates Cargo.toml Cargo.lock)

# Prints `key = value` from `[section]` of configuration $3 (this worktree's by
# default) without quotes. Only handles the simple values the generated
# configuration uses.
config_get() {
    sed -n "/^\[$1\]/,/^\[/{s/^$2 *= *\"\{0,1\}\([^\"]*\)\"\{0,1\} *\$/\1/p}" "${3:-$config_file}"
}

# Loads the instance's paths. Everything except the generated defaults is read
# from the configuration, so edits to it are respected.
load() {
    [[ -f $config_file ]] || die "$config_file is missing; write it with \`just dev config\`"
    data_dir=$(config_get server data_dir)
    runtime_dir=$(config_get server runtime_dir)
    docker_socket=$(config_get docker socket)
    [[ -n $data_dir && -n $runtime_dir ]] ||
        die "$config_file must set server.data_dir and server.runtime_dir"
    socket=$runtime_dir/piqueld.sock
    container=piqueld-dev-$(basename "$runtime_dir")
    pid_file=$runtime_dir/dev.pid
    daemon_pid_file=$runtime_dir/daemon.pid
    state_file=$runtime_dir/state
    build_started=$runtime_dir/build.started
    output_log=$runtime_dir/output.log
    daemon_log=$runtime_dir/daemon.log
    detached_log=$runtime_dir/dev.log
}

die() {
    printf '%s\n' "$*" >&2
    exit 1
}

# The instance is named after the worktree directory, or `main` for the main
# checkout, e.g. `t3code-b681a751`.
instance_name() {
    local main name
    main=$(git worktree list --porcelain | sed -n '1s/^worktree //p')
    name=main
    [[ $root == "$main" ]] || name=$(basename "$root")
    name=$(tr -cs 'a-z0-9' '-' <<<"${name,,}" | cut -c1-40)
    name=${name#-}
    printf '%s\n' "${name%-}"
}

generate_config() {
    local name state runtime port
    name=$(instance_name)
    # State stays out of /tmp, whose old files systemd may delete. Sockets use
    # /tmp because every session sees it, unlike /run/user.
    state=${XDG_STATE_HOME:-$HOME/.local/state}/piqueld-dev/$name
    runtime=/tmp/piqueld-dev/$name
    port=$(free_port)
    cat >"$config_file" <<EOF
# Development instance for this worktree, generated by \`just dev config\`.
# The dev scripts read the directories, port, public URL, and Docker socket
# from here. Unset settings use the daemon's defaults; see
# examples/piqueld.toml.

[server]
data_dir = "$state"
runtime_dir = "$runtime"
# The browser preview opens public_url; the Unix socket serves the CLI.
listen_mode = "localhost"
port = $port

[auth]
public_url = "http://localhost:$port"

[docker]
# A private Docker-in-Docker engine, started by \`just dev\`. Point this at
# /var/run/docker.sock to use the host engine instead.
socket = "$runtime/docker/docker.sock"
auto_initialize_swarm = true
EOF
    printf 'wrote %s for instance %s\n' "$config_file" "$name" >&2
}

# Prints the lowest port from 7846 that nothing listens on and no other
# worktree's configuration claims.
free_port() {
    local claimed=() dir port=7846
    while read -r dir; do
        [[ $dir != "$root" && -f $dir/$config_file ]] &&
            claimed+=("$(config_get server port "$dir/$config_file")")
    done < <(git worktree list --porcelain | sed -n 's/^worktree //p')
    while [[ " ${claimed[*]} " == *" $port "* || -n $(ss -Htln "sport = :$port") ]]; do
        port=$((port + 1))
    done
    echo "$port"
}

# Whether the pid in file $1 is alive.
alive() {
    [[ -f $1 ]] && kill -0 "$(<"$1")" 2>/dev/null
}

# Starts this instance's Docker engine when the configuration points at it.
# The container and its image store persist across restarts; `clean` removes
# them. The data directory is mounted at the same path because the daemon
# bind-mounts files from it, such as the ingress configuration.
start_docker() {
    [[ $docker_socket == "$runtime_dir/docker/docker.sock" ]] || return 0
    mkdir -p -m 0700 "$runtime_dir/docker" "$data_dir"
    if docker container inspect "$container" >/dev/null 2>&1; then
        # A restart recreates the socket when its directory was replaced
        # while the engine ran.
        if [[ -S $docker_socket ]]; then
            docker start "$container" >/dev/null
        else
            docker restart "$container" >/dev/null
        fi
    else
        docker run \
            --detach \
            --privileged \
            --name "$container" \
            --label "io.piqueld.dev.worktree=$root" \
            --label "io.piqueld.dev.data=$data_dir" \
            --label "io.piqueld.dev.runtime=$runtime_dir" \
            --env DOCKER_TLS_CERTDIR= \
            --volume "$container:/var/lib/docker" \
            --volume "$runtime_dir/docker:/piqueld-socket" \
            --volume "$data_dir:$data_dir" \
            "$dind_image" \
            dockerd --host=unix:///piqueld-socket/docker.sock \
            >/dev/null
    fi
    dind_wait "$container"
}

run() {
    [[ -f $config_file ]] || generate_config
    load
    if alive "$pid_file" && [[ $(<"$pid_file") != "$$" ]]; then
        die "already running (pid $(<"$pid_file")); see \`just dev status\`"
    fi
    mkdir -p -m 0700 "$runtime_dir"
    echo $$ >"$pid_file"
    start_docker

    declare -a child_pids=()
    cleanup() {
        local child deadline

        trap - EXIT
        # Repeated signals must not interrupt cleanup and orphan the daemon.
        trap '' INT TERM HUP

        # Each process is started in its own session so cargo-watch's child
        # and its build-script children are stopped with their supervisors.
        for child in "${child_pids[@]}"; do
            pkill -TERM --session "$child" 2>/dev/null || true
        done

        # The daemon allows ten seconds to finish in-flight requests. Watch may
        # exit first, so check the entire session and bound the grace period.
        deadline=$((SECONDS + 11))
        while ((SECONDS < deadline)); do
            local running=false
            for child in "${child_pids[@]}"; do
                if pgrep --session "$child" >/dev/null; then
                    running=true
                    break
                fi
            done
            "$running" || break
            sleep 0.1
        done

        # Reap supervisors only after terminating any unresponsive descendants.
        for child in "${child_pids[@]}"; do
            pkill -KILL --session "$child" 2>/dev/null || true
        done
        wait 2>/dev/null || true
        rm -f "$pid_file" "$daemon_pid_file" "$state_file"
    }
    handle_signal() {
        cleanup
        exit 0
    }
    trap cleanup EXIT
    trap handle_signal INT TERM HUP

    # The daemon embeds the dashboard at compile time, so the UI crate is
    # watched too: every dashboard edit re-runs the build script, which
    # rebuilds the bundle, and restarts the daemon.
    # Keep the command in the session managed by cleanup: cargo-watch otherwise
    # creates another session that survives if the watcher exits first. `serve`
    # execs the daemon, making it the watcher's direct child, so reloads still
    # stop and reap the daemon before starting its replacement.
    local watch=()
    for path in "${watched[@]}"; do watch+=(--watch "$path"); done
    setsid cargo watch --no-process-group "${watch[@]}" \
        --shell "exec bash scripts/dev.sh serve" &
    child_pids+=("$!")

    set +e
    wait -n "${child_pids[@]}"
    local status=$?
    set -e

    printf 'development process exited with status %d; stopping the remaining processes\n' "$status" >&2
    exit "$status"
}

# Builds the daemon, recording the outcome for `wait`, then replaces itself
# with it. Build output and the daemon's errors are also kept in output.log;
# its logs are appended to daemon.log as JSON.
serve() {
    load
    touch "$build_started"
    echo building >"$state_file"
    local color=never
    [[ -t 2 ]] && color=always
    if ! cargo build --package piqueld --bin piqueld --features embedded-ui --color "$color" 2>&1 |
        tee >(sed -u 's/\x1b\[[0-9;]*[mK]//g' >"$output_log"); then
        echo failed >"$state_file"
        exit 1
    fi
    echo running >"$state_file"
    echo $$ >"$daemon_pid_file"
    exec "${CARGO_TARGET_DIR:-target}/debug/piqueld" --config "$config_file" --log-file "$daemon_log" \
        2> >(tee -a "$output_log" >&2)
}

start() {
    [[ -f $config_file ]] || generate_config
    load
    if ! alive "$pid_file"; then
        mkdir -p -m 0700 "$runtime_dir"
        # A background job of a script is not a process group leader, so
        # setsid execs in place and $! is the instance's pid. Recording it here
        # lets `wait` start immediately.
        setsid bash scripts/dev.sh run >"$detached_log" 2>&1 </dev/null &
        echo $! >"$pid_file"
    fi
    wait_ready "${1:-}"
}

# Prints the instance's URL once the daemon serves the current sources. Fails
# with the relevant output when the build or startup fails.
wait_ready() {
    load
    local deadline=$((SECONDS + ${1:-900})) url
    while ((SECONDS < deadline)); do
        alive "$pid_file" || {
            [[ -f $detached_log ]] && tail -n 40 "$detached_log" >&2
            die "the instance is not running; start it with \`just dev start\`"
        }
        if [[ -f $build_started ]] &&
            [[ -z $(find "${watched[@]}" -newer "$build_started" -type f -print -quit) ]]; then
            case $(cat "$state_file" 2>/dev/null) in
            failed)
                tail -n 60 "$output_log" >&2
                die "the build failed; fix it and save to rebuild"
                ;;
            running)
                if ! alive "$daemon_pid_file"; then
                    tail -n 60 "$output_log" >&2
                    die "the daemon exited; fix it and save to rebuild"
                fi
                # The authentication status is served before initial setup,
                # unlike the socket's /health.
                url=$(curl -sf --max-time 2 --unix-socket "$socket" http://localhost/api/v1/auth/status |
                    grep -oE '"public_url":"[^"]*"' | cut -d'"' -f4 || true)
                if [[ -n $url ]]; then
                    printf 'ready: %s/dashboard/\n' "$url"
                    return 0
                fi
                ;;
            esac
        fi
        sleep 2
    done
    die "not ready after ${1:-900} seconds; see \`just dev status\`"
}

status() {
    load
    local state=stopped url=""
    if alive "$pid_file"; then
        state=$(cat "$state_file" 2>/dev/null || echo starting)
        url=$(curl -sf --max-time 2 --unix-socket "$socket" http://localhost/api/v1/auth/status |
            grep -oE '"public_url":"[^"]*"' | cut -d'"' -f4 || true)
    fi
    cat <<EOF
instance  $(basename "$runtime_dir") ($state)
url       ${url:-unavailable}${url:+/dashboard/}
socket    $socket
data      $data_dir
docker    $docker_socket
output    $output_log
logs      $daemon_log
EOF
}

stop() {
    load
    alive "$pid_file" || return 0
    kill -TERM "$(<"$pid_file")"
    for _ in {1..150}; do
        alive "$pid_file" || return 0
        sleep 0.1
    done
    die "the instance did not stop within 15 seconds"
}

# Removes a stopped instance's engine, its image store, and the given
# directories. Only directories under a `piqueld-dev` parent are deleted, so a
# configuration pointing elsewhere never loses data. Containers may have left
# root-owned files behind, which only a container can remove.
remove_instance() {
    local container=$1 dir parent
    shift
    docker rm --force --volumes "$container" >/dev/null 2>&1 || true
    docker volume rm "$container" >/dev/null 2>&1 || true
    for dir in "$@"; do
        parent=$(dirname "$dir")
        if [[ $(basename "$parent") != piqueld-dev ]]; then
            printf 'kept %s\n' "$dir" >&2
        elif ! rm -rf -- "$dir" 2>/dev/null; then
            docker run --rm --volume "$parent:/parent" --entrypoint rm "$dind_image" \
                -rf "/parent/$(basename "$dir")"
        fi
    done
}

clean() {
    stop
    remove_instance "$container" "$data_dir" "$runtime_dir"
    printf 'removed instance %s\n' "$(basename "$runtime_dir")" >&2
}

prune() {
    local container worktree
    for container in $(docker ps --all --quiet --filter label=io.piqueld.dev.worktree); do
        worktree=$(docker inspect --format '{{index .Config.Labels "io.piqueld.dev.worktree"}}' "$container")
        [[ -d $worktree ]] && continue
        remove_instance "$container" \
            "$(docker inspect --format '{{index .Config.Labels "io.piqueld.dev.data"}}' "$container")" \
            "$(docker inspect --format '{{index .Config.Labels "io.piqueld.dev.runtime"}}' "$container")"
        printf 'removed the instance of %s\n' "$worktree" >&2
    done
}

ctl() {
    load
    PIQUELD_SOCKET=$socket exec cargo run --quiet --package piquelctl -- "$@"
}

# Bash reads scripts as it runs them: parsing everything before running keeps
# an instance working while this file is edited.
main() {
    local command=${1:-run}
    [[ $# -gt 0 ]] && shift
    case $command in
    run | serve | status | stop | clean) "$command" ;;
    start) start "$@" ;;
    wait) wait_ready "$@" ;;
    prune) prune ;;
    ctl) ctl "$@" ;;
    config)
        if [[ ${1:-} == --force || ! -e $config_file ]]; then
            generate_config
        else
            printf 'kept %s; pass --force to replace it\n' "$config_file" >&2
        fi
        ;;
    *) die "unknown command: $command (see scripts/dev.sh)" ;;
    esac
}

main "$@"
exit
